import { REBuilder } from './rebuilder.ts'

//

/**
 * Recognition options for schemaless links.
 *
 * @category types
 */
export interface LinkifyOptions {
  /** Recognize URLs without `http(s)://` prefix. Default `false`. */
  fuzzyLink?: boolean
  /** Recognize emails without `mailto:` prefix. Default `true`. */
  fuzzyEmail?: boolean
  /**
   * Allow IPs in fuzzy links. Can conflict with some texts, like version
   * numbers. Default `false`.
   */
  fuzzyIP?: boolean
  /**
   * Terminate link with `---` if it is considered a long dash. Default `false`.
   */
  '---'?: boolean
}

export interface LinkifyConstructorOptions extends LinkifyOptions {
  /** Custom regular expression builder. */
  rebuilder?: REBuilder
}

const defaultOptions: Required<LinkifyOptions> = {
  fuzzyLink: false,
  fuzzyEmail: true,
  fuzzyIP: false,
  '---': false
}

/**
 * Custom schema definition.
 *
 * @category types
 */
export interface SchemaOpts {
  /**
   * Checks text after the schema prefix. Should return matched tail length on
   * success, or `0` on fail.
   */
  validate: (text: string, pos: number, self: LinkifyIt) => number
  /**
   * Optional function to normalize `text` and `url` of matched result, for
   * example for `@twitter` mentions.
   */
  normalize?: (match: Match, self: LinkifyIt) => void
}

type Schema = Required<SchemaOpts>

interface MatchCandidate {
  schema: string
  index: number
  lastIndex: number
}

const web_schema: Schema = {
  validate: (text: string, pos: number, self: LinkifyIt) => {
    const re = self.re.get_http_validator()
    re.lastIndex = pos

    const m = re.exec(text)
    return m ? m[0].length : 0
  },
  normalize: (match: Match, self: LinkifyIt) => self.normalize(match)
}

const defaultSchemas: Record<string, Schema> = {
  'http:': web_schema,
  'https:': web_schema,
  'ftp:': web_schema,
  '//': {
    validate: function (text: string, pos: number, self: LinkifyIt) {
      const re = self.re.get_relative_proto_validator()
      re.lastIndex = pos

      const m = re.exec(text)
      if (m) {
        // should not be `://` & `///`, that protects from errors in protocol name
        if (pos >= 3 && text[pos - 3] === ':') { return 0 }
        if (pos >= 3 && text[pos - 3] === '/') { return 0 }
        return m[0].length
      }
      return 0
    },
    normalize: (match: Match, self: LinkifyIt) => self.normalize(match)
  },
  'mailto:': {
    validate: function (text: string, pos: number, self: LinkifyIt) {
      const re = self.re.get_mailto_validator()
      re.lastIndex = pos

      const m = re.exec(text)
      return m ? m[0].length : 0
    },
    normalize: (match: Match, self: LinkifyIt) => self.normalize(match)
  }
}

// RE pattern for 2-character tlds (autogenerated by ./support/tlds_2char_gen.js)
const tlds_2ch_src = 'a[cdefgilmnoqrstuwxz]|b[abdefghijmnorstvwyz]|c[acdfghiklmnoruvwxyz]|d[ejkmoz]|e[cegrstu]|f[ijkmor]|g[abdefghilmnpqrstuwy]|h[kmnrtu]|i[delmnoqrst]|j[emop]|k[eghimnprwyz]|l[abcikrstuvy]|m[acdeghklmnopqrstuvwxyz]|n[acefgilopruz]|om|p[aefghklmnrstwy]|qa|r[eosuw]|s[abcdeghijklmnortuvxyz]|t[cdfghjklmnortvwz]|u[agksyz]|v[aceginu]|w[fs]|y[et]|z[amw]'

// DON'T try to make PRs with changes. Extend TLDs with LinkifyIt.tlds() instead
const tlds_default_src = 'biz|com|edu|gov|net|org|pro|web|xxx|aero|asia|coop|info|museum|name|shop|рф'

/**
 * Match result returned by {@link LinkifyIt.match} and
 * {@link LinkifyIt.matchAtStart}.
 *
 * @category types
 */
export class Match {
  /** Prefix (protocol) for matched string. Empty for fuzzy links. */
  schema: string
  /** First position of matched string. */
  index: number
  /** Next position after matched string. */
  lastIndex: number
  /** Matched string. */
  raw: string
  /** Normalized text of matched string. */
  text: string
  /** Normalized URL of matched string. */
  url: string

  constructor (text: string, schema: string, index: number, lastIndex: number) {
    const raw = text.slice(index, lastIndex)

    this.schema = schema.toLowerCase()
    this.index = index
    this.lastIndex = lastIndex
    this.raw = raw
    this.text = raw
    this.url = raw
  }
}

/** Linkifier instance. */
export class LinkifyIt {
  __opts__: Required<LinkifyOptions>
  private __schemas__: Record<string, Schema>
  __tlds_src__: string
  re: REBuilder

  /**
   * Creates new linkifier instance.
   *
   * By default understands:
   *
   * - `http(s)://...` , `ftp://...`, `mailto:...` & `//...` links
   * - "fuzzy" emails (foo@bar.com).
   *
   * See {@link LinkifyConstructorOptions} for available options.
   *
   * @param options Recognition options.
   *
   * @example
   * ```javascript
   * import { LinkifyIt } from 'linkify-it'
   *
   * const linkify = new LinkifyIt({ fuzzyLink: true })
   *
   * linkify
   *   .tlds(require('tlds'))       // Reload with full TLD list
   *   .tlds('onion', true)         // Add unofficial `.onion` domain
   *   .add('ftp:', null)           // Disable `ftp:` protocol
   *   .set({ fuzzyIP: true })      // Enable IPs in fuzzy links
   *
   * console.log(linkify.test('Site github.com!')) // true
   * console.log(linkify.match('Site github.com!'))
   * ```
   */
  constructor (options: LinkifyConstructorOptions = {}) {
    const { rebuilder, ...linkifyOptions } = options

    this.__opts__ = Object.assign({}, defaultOptions, linkifyOptions)

    this.__schemas__ = Object.assign({}, defaultSchemas)

    this.__tlds_src__ = tlds_default_src + '|' + tlds_2ch_src

    this.re = rebuilder || new REBuilder()
    this.re.set({
      ...this.__opts__,
      tlds_src: this.__tlds_src__,
      schema_names: Object.keys(this.__schemas__)
    })
  }

  /**
   * Add new rule definition.
   *
   * `schema` is a link prefix (usually, protocol name with `:` at the end,
   * `skype:` for example). `linkify-it` makes sure that prefix is not
   * preceded with alphanumeric char and symbols. Only whitespaces and
   * punctuation allowed.
   *
   * `definition` is a rule to check tail after link prefix. To disable an
   * existing rule, pass `null`.
   *
   * @param schema Rule name (fixed pattern prefix).
   * @param definition Schema definition, or `null` to disable the rule.
   *
   * @example
   * ```javascript
   * linkify.add('@', {
   *   validate (text, pos, self) {
   *     const tail = text.slice(pos)
   *     const twitter = new RegExp(
   *       `^([a-zA-Z0-9_]){1,15}(?!_)(?=$|${self.re.src_ZPCc})`
   *     )
   *
   *     const match = tail.match(twitter)
   *     if (!match) return 0
   *
   *     // Linkifier allows punctuation chars before prefix,
   *     // but we additionally disable `@` (`@@mention` is invalid).
   *     if (pos >= 2 && text[pos - 2] === '@') return 0
   *
   *     return match[0].length
   *   },
   *   normalize (match) {
   *     match.url = `https://twitter.com/${match.url.replace(/^@/, '')}`
   *   }
   * })
   * ```
   */
  add (schema: string, definition: SchemaOpts | null = null): this {
    if (!definition) {
      delete this.__schemas__[schema]
    } else {
      const def = Object.assign(
        { normalize: (match: Match, self: LinkifyIt) => self.normalize(match) },
        definition
      )
      this.__schemas__[schema] = def
    }

    this.re.set({ schema_names: Object.keys(this.__schemas__) })
    return this
  }

  /**
   * Set recognition options for links without schema.
   *
   * @param options Recognition options.
   */
  set (options: LinkifyOptions = {}): this {
    this.__opts__ = Object.assign(this.__opts__, options)
    this.re.set(options)
    return this
  }

  /**
   * Searches linkifiable pattern and returns `true` on success or `false` on fail.
   *
   * @param text Text to scan.
   */
  test (text: string): boolean {
    if (!text.length) { return false }

    let m, re

    // try to scan for link with schema - that's the most simple rule
    if (this.re.get_schema_test().test(text)) {
      re = this.re.get_schema_search()
      re.lastIndex = 0
      while ((m = re.exec(text)) !== null) {
        if (this.testSchemaAt(text, m[2], re.lastIndex)) { return true }
      }
    }

    if (this.__opts__.fuzzyLink && this.__schemas__['http:']) {
      // guess schemaless links
      if (text.search(this.re.get_host_fuzzy_test()) >= 0) {
        if (text.match(this.__opts__.fuzzyIP ? this.re.get_link_fuzzy() : this.re.get_link_no_ip_fuzzy()) !== null) {
          return true
        }
      }
    }

    if (this.__opts__.fuzzyEmail && this.__schemas__['mailto:']) {
      // guess schemaless emails
      if (text.indexOf('@') >= 0) {
        // We can't skip this check, because this cases are possible:
        // 192.168.1.1@gmail.com, my.in@example.com
        if (text.match(this.re.get_email_fuzzy()) !== null) { return true }
      }
    }

    return false
  }

  /**
   * Very quick check, that can give false positives. Returns true if link MAY BE
   * can exists. Can be used for speed optimization, when you need to check that
   * link NOT exists.
   *
   * @param text Text to scan.
   */
  pretest (text: string): boolean {
    return this.re.get_pretest().test(text)
  }

  /**
   * Similar to {@link LinkifyIt.test} but checks only specific protocol tail exactly
   * at given position. Returns length of found pattern (0 on fail).
   *
   * @param text Text to scan.
   * @param schema Rule (schema) name.
   * @param pos Text offset to check from.
   */
  testSchemaAt (text: string, schema: string, pos: number): number {
    // If not supported schema check requested - terminate
    if (!this.__schemas__[schema.toLowerCase()]) {
      return 0
    }
    return this.__schemas__[schema.toLowerCase()].validate(text, pos, this)
  }

  /**
   * Returns array of found link descriptions or `null` on fail. We strongly
   * recommend to use {@link LinkifyIt.test} first, for best speed.
   *
   * @param text Text to scan.
   */
  match (text: string): Match[] | null {
    const result: Match[] = []
    const type_schemed: MatchCandidate[] = []
    const type_fuzzy_link: MatchCandidate[] = []
    const type_fuzzy_email: MatchCandidate[] = []
    let m: RegExpExecArray | null
    let len: number
    let re: RegExp

    function choose (a: MatchCandidate | undefined, b: MatchCandidate | undefined) {
      if (!a) { return b }
      if (!b) { return a }
      if (a.index !== b.index) { return a.index < b.index ? a : b }
      return a.lastIndex >= b.lastIndex ? a : b
    }

    if (!text.length) { return null }

    // scan for links with schema
    if (this.re.get_schema_test().test(text)) {
      re = this.re.get_schema_search()
      re.lastIndex = 0
      while ((m = re.exec(text)) !== null) {
        len = this.testSchemaAt(text, m[2], re.lastIndex)
        if (len) {
          type_schemed.push({
            schema: m[2],
            index: m.index + m[1].length,
            lastIndex: m.index + m[0].length + len
          })
        }
      }
    }

    if (this.__opts__.fuzzyLink && this.__schemas__['http:']) {
      re = this.__opts__.fuzzyIP ? this.re.get_link_fuzzy_global() : this.re.get_link_no_ip_fuzzy_global()
      re.lastIndex = 0
      while ((m = re.exec(text)) !== null) {
        type_fuzzy_link.push({
          schema: '',
          index: m.index + m[1].length,
          lastIndex: m.index + m[0].length
        })
      }
    }

    if (this.__opts__.fuzzyEmail && this.__schemas__['mailto:']) {
      re = this.re.get_email_fuzzy_global()
      re.lastIndex = 0
      while ((m = re.exec(text)) !== null) {
        type_fuzzy_email.push({
          schema: 'mailto:',
          index: m.index + m[1].length,
          lastIndex: m.index + m[0].length
        })
      }
    }

    const indexes = [0, 0, 0]
    let lastIndex = 0

    for (;;) {
      const candidates = [
        type_schemed[indexes[0]],
        type_fuzzy_email[indexes[1]],
        type_fuzzy_link[indexes[2]]
      ]

      const candidate = choose(choose(candidates[0], candidates[1]), candidates[2])

      if (!candidate) { break }

      if (candidate === candidates[0]) {
        indexes[0]++
      } else if (candidate === candidates[1]) {
        indexes[1]++
      } else {
        indexes[2]++
      }

      if (candidate.index < lastIndex) { continue }

      const match = new Match(text, candidate.schema, candidate.index, candidate.lastIndex)
      if (match.schema) {
        this.__schemas__[match.schema].normalize(match, this)
      } else {
        this.normalize(match)
      }
      result.push(match)
      lastIndex = candidate.lastIndex
    }

    if (result.length) {
      return result
    }

    return null
  }

  /**
   * Returns fully-formed (not fuzzy) link if it starts at the beginning
   * of the string, and null otherwise.
   *
   * @param text Text to scan.
   */
  matchAtStart (text: string): Match | null {
    if (!text.length) return null

    const m = this.re.get_schema_at_start().exec(text)
    if (!m) return null

    const len = this.testSchemaAt(text, m[2], m[0].length)
    if (!len) return null

    const match = new Match(text, m[2], m.index + m[1].length, m.index + m[0].length + len)

    this.__schemas__[match.schema].normalize(match, this)
    return match
  }

  /**
   * Load (or merge) new TLDs list. Those are used for fuzzy links (without
   * prefix) to avoid false positives. By default this algorithm is used:
   *
   * - hostname with any 2-letter root zones are ok.
   * - biz|com|edu|gov|net|org|pro|web|xxx|aero|asia|coop|info|museum|name|shop|рф
   *   are ok.
   * - encoded (`xn--...`) root zones are ok.
   *
   * If list is replaced, then exact match for 2-chars root zones will be checked.
   *
   * @param list List of TLDs.
   * @param keepOld Merge with current list if `true` (`false` by default).
   */
  tlds (list: string | string[], keepOld = false): this {
    list = Array.isArray(list) ? list : [list]

    if (!keepOld) {
      this.__tlds_src__ = list.join('|')
    } else {
      this.__tlds_src__ += '|' + list.slice()
        .sort()
        .filter(function (el: string, idx: number, arr: string[]) {
          return el !== arr[idx - 1]
        })
        .reverse()
        .join('|')
    }

    this.re.set({ tlds_src: this.__tlds_src__ })
    return this
  }

  /**
   * Default normalizer (if schema does not define its own).
   *
   * @param match Match to normalize.
   */
  normalize (match: Match): void {
    // Do minimal possible changes by default. Need to collect feedback prior
    // to move forward https://github.com/markdown-it/linkify-it/issues/1

    if (!match.schema) { match.url = `http://${match.url}` }

    if (match.schema === 'mailto:' && !/^mailto:/i.test(match.url)) {
      match.url = `mailto:${match.url}`
    }
  }
}

function linkifyit (options: LinkifyConstructorOptions = {}): LinkifyIt {
  return new LinkifyIt(options)
}

export { linkifyit }
